type Todo {
  id: ID!
  title: String!
  user: String!
}

input TodoInput {
  id: ID!
  title: String!
  user: String!
}

type Query {
  getTodos: [Todo!]
}

type Mutation {
  addTodo(todo: TodoInput!): Todo
  deleteTodo(todoId: String!): String
}